services:
  - type: web
    name: smart-recipe-generator
    env: node
    plan: free
    buildCommand: cd frontend && npm install && npm run build
    startCommand: cd frontend && npm run preview --port $PORT
    staticPublishPath: ./frontend/dist
    envVars:
      - key: NODE_VERSION
        value: 18.17.0
